[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/tools"
  to = "/tools.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/case-studies"
  to = "/case-studies.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/website.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/index-1.html"
  to = "/"
  status = 301
